### ISSUE TITLE
Simpler random Unsplash images

### ISSUE THREAD

**Issue by oliverjam** [fac21/week6-app-jcnr#39]
https://github.com/fac21/week6-app-jcnr/blob/2da645ac98554014bf6bc9bf69c7cc328108b238/templates.js#L33-L44

This code is cool, and it's great to practice client-side stuff like fetching (since we're spending so much time on the server).

However there is a much simpler way to achieve this: https://source.unsplash.com/

You can construct a URL like `https://source.unsplash.com/random/1000/800` to get a random picture of those dimensions. It even supports search terms by adding search params like `?skateboard,banana` to the end.

This would allow you to simply use that URL as a CSS background-image for the page:

```css
html {
  background-image: url('https://source.unsplash.com/random/1000/800');
  background-size: cover;
}
```
